"use client";

import { useState } from "react";
import Image from "next/image";

const showcases = [
  {
    id: "quote",
    label: "Quote",
    command: "Quote This Message",
    eyebrow: "Make it memorable",
    title: "Turn a message into something worth saving.",
    description: "Open the message menu, choose Pocket Tool, then shape the result with fonts, fitting, colour and effects before you share it.",
    image: "/assets/quote/quote.png",
    width: 684,
    height: 681,
    imageAlt: "Pocket Tool quote creator inside Discord",
    details: ["Message command", "Custom type", "Visual effects"],
  },
  {
    id: "timestamp",
    label: "Timestamp",
    command: "/timestamp",
    eyebrow: "No timezone maths",
    title: "Say when, clearly, for everyone.",
    description: "Write natural times like “in 10 minutes”, pick any timezone and choose the Discord timestamp style that fits the message.",
    image: "/assets/time/timestamp_zone_focus.png",
    width: 900,
    height: 606,
    imageAlt: "Pocket Tool timestamp timezone autocomplete in Discord",
    details: ["Natural language", "Global zones", "9 display styles"],
  },
  {
    id: "tts",
    label: "Text to Speech",
    command: "/tts",
    eyebrow: "Text, now with a voice",
    title: "Make a Discord voice message from any text.",
    description: "Choose a language and voice, then Pocket Tool returns a native voice message you can play directly in the conversation.",
    image: "/assets/tts/audio.png",
    width: 346,
    height: 141,
    imageAlt: "A voice message generated by Pocket Tool in Discord",
    details: ["Native voice message", "Locale aware", "Three voice styles"],
  },
  {
    id: "tweet",
    label: "Tweet",
    command: "/tweet",
    eyebrow: "Links that read well",
    title: "Bring a post into the conversation—cleanly.",
    description: "Preview X posts with media, engagement details and an optional translation into your chosen language.",
    image: "/assets/tweet/ptbr.png",
    width: 518,
    height: 264,
    imageAlt: "Translated tweet preview made by Pocket Tool in Discord",
    details: ["Rich previews", "Optional translation", "Direct source link"],
  },
] as const;

export function CommandShowcase() {
  const [active, setActive] = useState(0);
  const item = showcases[active];

  return (
    <div className="showcase" data-reveal>
      <div className="showcase-tabs" role="tablist" aria-label="Featured Pocket Tool commands">
        {showcases.map((showcase, index) => (
          <button
            key={showcase.id}
            type="button"
            role="tab"
            aria-selected={active === index}
            aria-controls="showcase-panel"
            className={active === index ? "is-active" : ""}
            onClick={() => setActive(index)}
          >
            <span>{String(index + 1).padStart(2, "0")}</span>
            {showcase.label}
          </button>
        ))}
      </div>

      <div className="showcase-panel" id="showcase-panel" role="tabpanel" key={item.id}>
        <div className="showcase-copy">
          <p className="eyebrow">{item.eyebrow}</p>
          <p className="command-chip"><span aria-hidden="true">›</span> {item.command}</p>
          <h3>{item.title}</h3>
          <p>{item.description}</p>
          <ul className="detail-list" aria-label="Highlights">
            {item.details.map((detail) => <li key={detail}>{detail}</li>)}
          </ul>
          <a className="text-link" href={`/docs#${item.id}`}>Read command details <span aria-hidden="true">→</span></a>
        </div>
        <div className="showcase-media">
          <div className="showcase-media__bar">
            <span><i></i><i></i><i></i></span>
            <span>discord · pocket-tool</span>
          </div>
          <div className="showcase-media__canvas">
            <Image src={item.image} alt={item.imageAlt} width={item.width} height={item.height} sizes="(max-width: 860px) 92vw, 55vw" unoptimized />
          </div>
        </div>
      </div>
    </div>
  );
}
