"use client";

import { useCallback, useEffect, useLayoutEffect, useRef, useState } from "react";
import Image from "next/image";
import Link from "next/link";

const showcases = [
  {
    id: "quote",
    label: "Quote",
    command: "Quote This Message",
    eyebrow: "Make it memorable",
    title: "Turn a message into something worth saving.",
    description: "Open the message menu, choose Pocket Tool, then shape the result with fonts, fitting, colour and effects before you share it.",
    image: "/assets/quote/quote.png",
    width: 684,
    height: 681,
    imageAlt: "Pocket Tool quote creator inside Discord",
    details: ["Custom Type", "Visual Effects"],
  },
  {
    id: "time",
    label: "Timestamp",
    command: "/timestamp",
    eyebrow: "No timezone maths",
    title: "Say when, clearly, for everyone.",
    description: "Write natural times like \"in 10 minutes\", pick any timezone and choose the Discord timestamp style that fits the message.",
    image: "/assets/time/timestamp_zone_focus.png",
    width: 900,
    height: 606,
    imageAlt: "Pocket Tool timestamp timezone autocomplete in Discord",
    details: ["Natural Language", "Global Zones", "9 Display Styles"],
  },
  {
    id: "tts",
    label: "TTS",
    command: "/tts",
    eyebrow: "Text, now with a voice",
    title: "Make a Discord voice message from any text.",
    description: "Choose a language and voice, then Pocket Tool returns a native voice message you can play directly in the conversation.",
    image: "/assets/tts/audio.png",
    width: 346,
    height: 141,
    imageAlt: "A voice message generated by Pocket Tool in Discord",
    details: ["Native Voice Message", "Locale Aware", "Three Voice Styles"],
  },
  {
    id: "tweet",
    label: "Tweet",
    command: "/tweet",
    eyebrow: "Links that read well",
    title: "Bring a post into the conversation.",
    description: "Preview X posts with media, engagement details and an optional translation into your chosen language.",
    image: "/assets/tweet/ptbr.png",
    width: 518,
    height: 264,
    imageAlt: "Translated tweet preview made by Pocket Tool in Discord",
    details: ["Rich Previews", "Optional Translation", "Direct Source Link"],
  },
] as const;

const AUTOPLAY_MS = 6000;

export function CommandShowcase() {
  const [active, setActive] = useState(0);
  const [direction, setDirection] = useState<"next" | "prev">("next");
  const [paused, setPaused] = useState(false);
  const [indicator, setIndicator] = useState<{ left: number; width: number } | null>(null);
  const tabRefs = useRef<(HTMLButtonElement | null)[]>([]);
  const item = showcases[active];

  const goTo = useCallback((index: number, dir: "next" | "prev") => {
    setDirection(dir);
    setActive(index);
  }, []);

  const handleTabClick = (index: number) => {
    if (index === active) return;
    goTo(index, index > active ? "next" : "prev");
  };

  const handleTabKeyDown = (event: React.KeyboardEvent<HTMLButtonElement>, index: number) => {
    if (event.key !== "ArrowRight" && event.key !== "ArrowLeft") return;
    event.preventDefault();
    const nextIndex = event.key === "ArrowRight"
      ? (index + 1) % showcases.length
      : (index - 1 + showcases.length) % showcases.length;
    goTo(nextIndex, event.key === "ArrowRight" ? "next" : "prev");
    tabRefs.current[nextIndex]?.focus();
  };

  useLayoutEffect(() => {
    const btn = tabRefs.current[active];
    if (btn) {
      setIndicator({ left: btn.offsetLeft, width: btn.offsetWidth });
    }
  }, [active]);

  useEffect(() => {
    function syncIndicator() {
      const btn = tabRefs.current[active];
      if (btn) setIndicator({ left: btn.offsetLeft, width: btn.offsetWidth });
    }
    window.addEventListener("resize", syncIndicator);
    return () => window.removeEventListener("resize", syncIndicator);
  }, [active]);

  useEffect(() => {
    if (paused) return;
    if (typeof window !== "undefined" && window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

    const timer = window.setTimeout(() => {
      goTo((active + 1) % showcases.length, "next");
    }, AUTOPLAY_MS);

    return () => window.clearTimeout(timer);
  }, [active, paused, goTo]);

  return (
    <div
      className="showcase"
      data-reveal
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
      onFocus={() => setPaused(true)}
      onBlur={(event) => {
        if (!event.currentTarget.contains(event.relatedTarget as Node)) setPaused(false);
      }}
    >
      <div className="showcase-tabs" role="tablist" aria-label="Featured Pocket Tool commands">
        {indicator && (
          <span
            className="showcase-tabs__indicator"
            style={{ transform: `translateX(${indicator.left}px)`, width: indicator.width }}
            aria-hidden="true"
          />
        )}
        {showcases.map((showcase, index) => (
          <button
            key={showcase.id}
            ref={(el) => { tabRefs.current[index] = el; }}
            type="button"
            role="tab"
            tabIndex={active === index ? 0 : -1}
            aria-selected={active === index}
            aria-controls="showcase-panel"
            className={active === index ? "is-active" : ""}
            onClick={() => handleTabClick(index)}
            onKeyDown={(event) => handleTabKeyDown(event, index)}
          >
            <span>{String(index + 1).padStart(2, "0")}</span>
            {showcase.label}
            {active === index && (
              <i
                className="showcase-tabs__progress"
                key={paused ? `${index}-paused` : `${index}-running`}
                style={{ animationPlayState: paused ? "paused" : "running" }}
                aria-hidden="true"
              />
            )}
          </button>
        ))}
      </div>

      <div className="showcase-panel" id="showcase-panel" role="tabpanel" key={item.id} data-direction={direction}>
        <div className="showcase-copy">
          <p className="eyebrow">{item.eyebrow}</p>
          <p className="command-chip"><span aria-hidden="true">›</span> {item.command}</p>
          <h3>{item.title}</h3>
          <p>{item.description}</p>
          <ul className="detail-list" aria-label="Highlights">
            {item.details.map((detail) => <li key={detail}>{detail}</li>)}
          </ul>
          <Link className="text-link" href={`/docs#${item.id}`}>Read command details</Link>
        </div>
        <div className="showcase-media">
          <div className="showcase-media__bar">
            <span><i></i><i></i><i></i></span>
            <span>discord - pocket-tool</span>
          </div>
          <div className="showcase-media__canvas">
            <Image src={item.image} alt={item.imageAlt} width={item.width} height={item.height} sizes="(max-width: 860px) 92vw, 55vw" unoptimized />
          </div>
        </div>
      </div>
    </div>
  );
}
